# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Berkay Kaya
tagline:          The Jekyll Butler
url:              http://berkaykaya.com
paginate:         1
baseurl:          /
author:
  name:           Berkay Kaya
  url:            https://twitter.com/berkayk
  email:          berkayk@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/berkayk/berkayk.github.io
